class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror4'
        self.UnzipMirrorCommand = 'unzipmirror4'
        self.TarMirrorCommand = 'tarmirror4'
        self.CancelMirror = 'cancel4'
        self.CancelAllCommand = 'cancelall4'
        self.ListCommand = 'list4'
        self.StatusCommand = 'status4'
        self.AuthorizedUsersCommand = 'users5'
        self.AuthorizeCommand = 'authorize4'
        self.UnAuthorizeCommand = 'unauthorize4'
        self.AddSudoCommand = 'addsudo4'
        self.RmSudoCommand = 'rmsudo4'
        self.PingCommand = 'ping4'
        self.RestartCommand = 'restart4'
        self.StatsCommand = 'stats4'
        self.HelpCommand = 'help4'
        self.LogCommand = 'log4'
        self.SpeedCommand = 'speedtest4'
        self.CloneCommand = 'clone4'
        self.WatchCommand = 'watch4'
        self.TarWatchCommand = 'tarwatch4'
        self.DeleteCommand = 'del4'
        self.UsageCommand = 'usage4'
        self.RepoCommand = 'repo4'
        self.OwnerCommand = 'owner4'
        self.ConfigCommand = 'config4'

BotCommands = _BotCommands()
